#!/usr/bin/env bash
set -euo pipefail

# Daily Health Check Script
# Runs comprehensive system validation and generates health report
# Can be run via cron: 0 9 * * * /path/to/daily_health_check.sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$PROJECT_ROOT"

REPORT_DIR="docs/ops"
REPORT_FILE="$REPORT_DIR/DAILY_HEALTH_REPORT.md"
TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
DATE_STAMP=$(date -u +"%Y-%m-%d")

mkdir -p "$REPORT_DIR"

echo "🏥 Running Daily Health Check - $TIMESTAMP"

# Initialize report
cat > "$REPORT_FILE" << EOF
# Daily Health Report

**Date**: $TIMESTAMP
**Generated by**: Autonomous Health Check System

---

## Executive Summary

EOF

# Track overall status
OVERALL_STATUS="✅ HEALTHY"
ISSUES_FOUND=0

# 1. Directory Structure Check
echo "📁 Checking directory structure..."
cat >> "$REPORT_FILE" << 'EOF'
## 1. Directory Structure

EOF

if [ -d "ReDNACoreDemo/core" ]; then
    echo "  ✅ Core module exists" >> "$REPORT_FILE"
else
    echo "  ❌ Core module missing" >> "$REPORT_FILE"
    OVERALL_STATUS="❌ UNHEALTHY"
    ((ISSUES_FOUND++))
fi

if [ -d "web" ]; then
    echo "  ✅ Web frontend exists" >> "$REPORT_FILE"
else
    echo "  ⚠️  Web frontend missing" >> "$REPORT_FILE"
    ((ISSUES_FOUND++))
fi

# Check for stray core/ directory
if [ -d "core" ]; then
    echo "  ⚠️  Stray core/ directory found (should only be ReDNACoreDemo/core/)" >> "$REPORT_FILE"
    ((ISSUES_FOUND++))
else
    echo "  ✅ No stray core/ directory" >> "$REPORT_FILE"
fi

# 2. Python Cache Cleanup
echo "🧹 Checking Python caches..."
cat >> "$REPORT_FILE" << 'EOF'

## 2. Python Cache Status

EOF

PYCACHE_COUNT=$(find . -type d -name "__pycache__" 2>/dev/null | wc -l | tr -d ' ')
PYC_COUNT=$(find . -name "*.pyc" 2>/dev/null | wc -l | tr -d ' ')

echo "  - \`__pycache__\` directories: $PYCACHE_COUNT" >> "$REPORT_FILE"
echo "  - \`.pyc\` files: $PYC_COUNT" >> "$REPORT_FILE"

if [ "$PYCACHE_COUNT" -gt 3000 ] || [ "$PYC_COUNT" -gt 20000 ]; then
    echo "  ⚠️  High cache count - consider cleanup" >> "$REPORT_FILE"
    ((ISSUES_FOUND++))
else
    echo "  ✅ Cache levels acceptable" >> "$REPORT_FILE"
fi

# 3. Import Validation
echo "🐍 Validating Python imports..."
cat >> "$REPORT_FILE" << 'EOF'

## 3. Import Validation

EOF

if PYTHONPATH=.:ReDNACoreDemo python3 -c "from ReDNACoreDemo.core import api" 2>/dev/null; then
    echo "  ✅ Core API imports successfully" >> "$REPORT_FILE"
else
    echo "  ❌ Core API import failed" >> "$REPORT_FILE"
    OVERALL_STATUS="❌ UNHEALTHY"
    ((ISSUES_FOUND++))
fi

if PYTHONPATH=.:ReDNACoreDemo python3 -c "from ReDNACoreDemo.core.policy import evaluate_nudge_policy, evaluate_capability" 2>/dev/null; then
    echo "  ✅ Policy module imports successfully" >> "$REPORT_FILE"
else
    echo "  ❌ Policy module import failed" >> "$REPORT_FILE"
    OVERALL_STATUS="❌ UNHEALTHY"
    ((ISSUES_FOUND++))
fi

# 4. Test Suite Quick Check
echo "🧪 Running smoke tests..."
cat >> "$REPORT_FILE" << 'EOF'

## 4. Test Suite Status

EOF

if PYTHONPATH=.:ReDNACoreDemo python3 -m pytest ReDNACoreDemo/tests/test_policy.py -q --tb=line > /tmp/health_test_output.txt 2>&1; then
    PASSED=$(grep "passed" /tmp/health_test_output.txt | grep -o "[0-9]* passed" | cut -d' ' -f1)
    echo "  ✅ Policy tests passed ($PASSED tests)" >> "$REPORT_FILE"
else
    echo "  ❌ Policy tests failed" >> "$REPORT_FILE"
    OVERALL_STATUS="❌ UNHEALTHY"
    ((ISSUES_FOUND++))
fi

# 5. Service Port Check
echo "🔌 Checking service ports..."
cat >> "$REPORT_FILE" << 'EOF'

## 5. Service Status

EOF

if curl -s -f http://localhost:8015/health > /dev/null 2>&1; then
    echo "  ✅ Core API (8015): Running" >> "$REPORT_FILE"
else
    echo "  ⚠️  Core API (8015): Not running" >> "$REPORT_FILE"
fi

if curl -s -f http://localhost:8100/health > /dev/null 2>&1; then
    echo "  ✅ DevX Backend (8100): Running" >> "$REPORT_FILE"
else
    echo "  ⚠️  DevX Backend (8100): Not running" >> "$REPORT_FILE"
fi

if curl -s http://localhost:3100 2>&1 | grep -q "html\|HTML"; then
    echo "  ✅ DevX Frontend (3100): Running" >> "$REPORT_FILE"
else
    echo "  ⚠️  DevX Frontend (3100): Not running" >> "$REPORT_FILE"
fi

# 6. Git Status Check
echo "📊 Checking git status..."
cat >> "$REPORT_FILE" << 'EOF'

## 6. Git Repository Status

EOF

GIT_STATUS_COUNT=$(git status --porcelain 2>/dev/null | wc -l | tr -d ' ')
CURRENT_BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")

echo "  - Current branch: \`$CURRENT_BRANCH\`" >> "$REPORT_FILE"
echo "  - Git status entries: $GIT_STATUS_COUNT" >> "$REPORT_FILE"

if [ "$GIT_STATUS_COUNT" -gt 1000 ]; then
    echo "  ⚠️  High git status count - consider running git hygiene" >> "$REPORT_FILE"
    ((ISSUES_FOUND++))
elif [ "$GIT_STATUS_COUNT" -gt 500 ]; then
    echo "  ⚠️  Moderate git status count" >> "$REPORT_FILE"
else
    echo "  ✅ Git status count acceptable" >> "$REPORT_FILE"
fi

# 7. Disk Usage Check
echo "💾 Checking disk usage..."
cat >> "$REPORT_FILE" << 'EOF'

## 7. Disk Usage

EOF

if command -v du > /dev/null 2>&1; then
    WEB_SIZE=$(du -sh web 2>/dev/null | cut -f1 || echo "N/A")
    CORE_SIZE=$(du -sh ReDNACoreDemo 2>/dev/null | cut -f1 || echo "N/A")
    DATA_SIZE=$(du -sh data 2>/dev/null | cut -f1 || echo "N/A")

    echo "  - Web: $WEB_SIZE" >> "$REPORT_FILE"
    echo "  - ReDNACoreDemo: $CORE_SIZE" >> "$REPORT_FILE"
    echo "  - Data: $DATA_SIZE" >> "$REPORT_FILE"
else
    echo "  ⚠️  du command not available" >> "$REPORT_FILE"
fi

# 8. iCloud Backup Status
echo "☁️  Checking iCloud backups..."
cat >> "$REPORT_FILE" << 'EOF'

## 8. iCloud Backup Status

EOF

ICLOUD_BACKUP_DIR="$HOME/Library/Mobile Documents/com~apple~CloudDocs/ReDNA_Backups"

if [ -d "$ICLOUD_BACKUP_DIR" ]; then
    echo "  ✅ iCloud backup directory exists" >> "$REPORT_FILE"

    # Count backup files
    BACKUP_COUNT=$(find "$ICLOUD_BACKUP_DIR" -name "*.tar.gz" 2>/dev/null | wc -l | tr -d ' ')
    echo "  - Total backups: $BACKUP_COUNT" >> "$REPORT_FILE"

    if [ "$BACKUP_COUNT" -gt 0 ]; then
        # Find the most recent backup
        LATEST_BACKUP=$(find "$ICLOUD_BACKUP_DIR" -name "*.tar.gz" -type f 2>/dev/null | head -1)

        if [ -n "$LATEST_BACKUP" ]; then
            # Get the age of the most recent backup in seconds
            if [ "$(uname)" = "Darwin" ]; then
                # macOS
                BACKUP_TIME=$(stat -f %m "$LATEST_BACKUP" 2>/dev/null || echo "0")
            else
                # Linux
                BACKUP_TIME=$(stat -c %Y "$LATEST_BACKUP" 2>/dev/null || echo "0")
            fi

            CURRENT_TIME=$(date +%s)
            BACKUP_AGE=$((CURRENT_TIME - BACKUP_TIME))
            BACKUP_AGE_HOURS=$((BACKUP_AGE / 3600))

            # Check if backup is less than 24 hours old
            if [ "$BACKUP_AGE" -lt 86400 ]; then
                echo "  ✅ Latest backup is up to date (${BACKUP_AGE_HOURS}h ago)" >> "$REPORT_FILE"
            else
                BACKUP_AGE_DAYS=$((BACKUP_AGE / 86400))
                echo "  ⚠️  Latest backup is ${BACKUP_AGE_DAYS} days old" >> "$REPORT_FILE"
                ((ISSUES_FOUND++))
            fi

            # Show backup file info
            BACKUP_NAME=$(basename "$LATEST_BACKUP")
            BACKUP_SIZE=$(du -h "$LATEST_BACKUP" 2>/dev/null | cut -f1 || echo "N/A")
            echo "  - Latest: \`$BACKUP_NAME\` ($BACKUP_SIZE)" >> "$REPORT_FILE"
        fi
    else
        echo "  ⚠️  No backups found in iCloud directory" >> "$REPORT_FILE"
        ((ISSUES_FOUND++))
    fi
else
    echo "  ⚠️  iCloud backup directory not found" >> "$REPORT_FILE"
    echo "  - Expected: \`$ICLOUD_BACKUP_DIR\`" >> "$REPORT_FILE"
    echo "  - Run \`bash scripts/backups/create_backup.sh\` to create initial backup" >> "$REPORT_FILE"
    ((ISSUES_FOUND++))
fi

# 9. Backup Retention Summary
echo "♻️  Checking backup retention..."
cat >> "$REPORT_FILE" << 'EOF'

## 9. Backup Retention Summary

EOF

# Run retention cleanup in dry-run mode
if [ -f "scripts/backups/retention_cleanup.sh" ]; then
    # Run the retention script and capture stats
    bash scripts/backups/retention_cleanup.sh > /tmp/retention_output.txt 2>&1
    RETENTION_EXIT_CODE=$?

    # Read stats files if they exist
    LOCAL_STATS=""
    ICLOUD_STATS=""

    if [ -f "/tmp/retention_Local_Backups.stats" ]; then
        LOCAL_STATS=$(cat /tmp/retention_Local_Backups.stats)
    fi

    if [ -f "/tmp/retention_iCloud_Backups.stats" ]; then
        ICLOUD_STATS=$(cat /tmp/retention_iCloud_Backups.stats)
    fi

    # Parse local stats (format: total|keep|delete|size|newest_age|oldest_age)
    if [ -n "$LOCAL_STATS" ]; then
        IFS='|' read -r LOCAL_TOTAL LOCAL_KEEP LOCAL_DELETE LOCAL_SIZE LOCAL_NEWEST LOCAL_OLDEST <<< "$LOCAL_STATS"
        echo "  **Local Backups** (\`~/Documents/ReDNA_Demos/backups\`):" >> "$REPORT_FILE"
        echo "  - Total: $LOCAL_TOTAL backups" >> "$REPORT_FILE"
        echo "  - Newest: ${LOCAL_NEWEST}d ago | Oldest: ${LOCAL_OLDEST}d ago" >> "$REPORT_FILE"
        echo "  - Keep: $LOCAL_KEEP | Would delete: $LOCAL_DELETE (size: $LOCAL_SIZE)" >> "$REPORT_FILE"
        echo "" >> "$REPORT_FILE"
    else
        echo "  **Local Backups**: No backups found" >> "$REPORT_FILE"
        echo "" >> "$REPORT_FILE"
    fi

    # Parse iCloud stats
    if [ -n "$ICLOUD_STATS" ]; then
        IFS='|' read -r ICLOUD_TOTAL ICLOUD_KEEP ICLOUD_DELETE ICLOUD_SIZE ICLOUD_NEWEST ICLOUD_OLDEST <<< "$ICLOUD_STATS"
        echo "  **iCloud Backups** (\`~/Library/Mobile Documents/.../ReDNA_Backups\`):" >> "$REPORT_FILE"
        echo "  - Total: $ICLOUD_TOTAL backups" >> "$REPORT_FILE"
        echo "  - Newest: ${ICLOUD_NEWEST}d ago | Oldest: ${ICLOUD_OLDEST}d ago" >> "$REPORT_FILE"
        echo "  - Keep: $ICLOUD_KEEP | Would delete: $ICLOUD_DELETE (size: $ICLOUD_SIZE)" >> "$REPORT_FILE"
        echo "" >> "$REPORT_FILE"
    else
        echo "  **iCloud Backups**: No backups found or directory missing" >> "$REPORT_FILE"
        echo "" >> "$REPORT_FILE"
    fi

    # Report retention policy
    echo "  **Retention Policy**:" >> "$REPORT_FILE"
    echo "  - Local: Keep 30 days" >> "$REPORT_FILE"
    echo "  - iCloud: Keep 60 days" >> "$REPORT_FILE"
    echo "  - Always keeps newest backup regardless of age" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"

    # Status based on exit code
    case $RETENTION_EXIT_CODE in
        0)
            echo "  ✅ Retention status: OK" >> "$REPORT_FILE"
            ;;
        2)
            echo "  ⚠️  Retention status: Warnings (see details above)" >> "$REPORT_FILE"
            ((ISSUES_FOUND++))
            ;;
        3)
            echo "  ❌ Retention status: Errors" >> "$REPORT_FILE"
            OVERALL_STATUS="❌ UNHEALTHY"
            ((ISSUES_FOUND++))
            ;;
    esac

    echo "" >> "$REPORT_FILE"
    echo "  **Next Action**: Run \`bash scripts/backups/retention_cleanup.sh --apply\` to delete old backups" >> "$REPORT_FILE"

    # Clean up temp files
    rm -f /tmp/retention_output.txt /tmp/retention_Local_Backups.stats /tmp/retention_iCloud_Backups.stats
else
    echo "  ⚠️  Retention script not found" >> "$REPORT_FILE"
    echo "  - Expected: \`scripts/backups/retention_cleanup.sh\`" >> "$REPORT_FILE"
    ((ISSUES_FOUND++))
fi

# Final Summary
cat >> "$REPORT_FILE" << EOF

---

## Overall Status

**Status**: $OVERALL_STATUS
**Issues Found**: $ISSUES_FOUND

EOF

if [ "$ISSUES_FOUND" -eq 0 ]; then
    cat >> "$REPORT_FILE" << 'EOF'
All systems operational. No action required.

EOF
else
    cat >> "$REPORT_FILE" << 'EOF'
Some issues detected. Review details above and take corrective action.

### Recommended Actions

- Run \`python3 scripts/git_sanity/scan_status.py\` for detailed git analysis
- Check service logs in \`.run/\` directory
- Review test failures with \`PYTHONPATH=.:ReDNACoreDemo python3 -m pytest -v\`

EOF
fi

cat >> "$REPORT_FILE" << 'EOF'
---

**Next Check**: Scheduled for tomorrow
**Report Archive**: `docs/ops/health_archive/`

EOF

echo "✅ Health check complete. Report: $REPORT_FILE"
echo ""
echo "Summary: $OVERALL_STATUS ($ISSUES_FOUND issues)"

# Archive the report
ARCHIVE_DIR="$REPORT_DIR/health_archive"
mkdir -p "$ARCHIVE_DIR"
cp "$REPORT_FILE" "$ARCHIVE_DIR/health_$DATE_STAMP.md"

exit 0
