from __future__ import annotations
from typing import Any, Dict


def build_bundle(
    *,
    user_id: str,
    snapshot_id: str,
    aggregate: Dict[str, Any],
    evidence_meta: Dict[str, Any],
    run_meta: Dict[str, Any],
) -> Dict[str, Any]:
    per_dna = aggregate.get("ucn_per_dna", {})
    descriptors = aggregate.get("descriptors", {})

    overall = aggregate.get("overall_ucn")
    if overall is None and per_dna:
        overall = sum(per_dna.values()) / max(1, len(per_dna))

    for path, payload in descriptors.items():
        payload.setdefault("ucn", per_dna.get(path, 0.0))

    bundle = {
        "schema_version": "explorer.bundle/1.1",
        "source": {
            "core_schema": "core/3.1",
            "ucnrr_schema": "ucnrr.demo/1.6",
        },
        "identity": {"user_id": user_id, "snapshot_id": snapshot_id},
        "paths_present": [[*path.split(".")] for path in sorted(descriptors.keys())],
        "results": {
            "schema_version": "ucnrr.demo/1.6",
            "ucn": {
                "per_dna": per_dna,
                "top_level": {"PaDNA": overall},
                "overall": overall,
            },
            "descriptors": descriptors,
            "curiosity": {"overall": aggregate.get("curiosity_overall")},
            "rr": {
                "overall": max(0.0, 1000.0 - (aggregate.get("curiosity_overall") or 0.0))
                if aggregate.get("curiosity_overall") is not None
                else None,
            },
            "gaps": aggregate.get("agenda", {}),
            "contradictions": aggregate.get("contradictions", []),
            "evidence_meta": {
                "provenance": run_meta,
                "images": evidence_meta.get("images", []),
                "observations": evidence_meta.get("observations", []),
            },
            "meta": {
                "difficulty": aggregate.get("difficulty", "normal"),
                "photo_coach_version": run_meta.get("model_version"),
            },
        },
        "notes": "Generated by PhotoRefinementCoach — outbound descriptor bundle",
    }

    if evidence_meta.get("contradictions"):
        bundle["results"].setdefault("debug", {})["contradictions"] = evidence_meta["contradictions"]

    return bundle
